[package]
name = "verovio-sys"
description = "Low-level cxx bridge to the Verovio music engraving library."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
links = "verovio"

[dependencies]
cxx.workspace = true

[build-dependencies]
cxx-build.workspace = true
cc.workspace = true
